version: "3.0"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=8Fny?aXEFkh9ePA3
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  ekila-streams:
    build:
      context: .
      dockerfile: Dockerfile
    image: ekilastreams-back:1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=8Fny?aXEFkh9ePA3  # Added to match db
    volumes:
      - .:/app
      - staticfiles-data:/var/www/static
      - media-data:/var/www/media
    depends_on:
      - db
      - redis
    ports:
      - "8030:8030"

volumes:
  postgres-data:
  staticfiles-data:
  media-data: